const DB='eigomimi-v9',VER=1;let db;
const $=id=>document.getElementById(id);
let state={lesson:1,book:false,current:null,queue:[],idx:-1,repeat:false,A:null,B:null,ab:false,editing:null,recording:null,dark:true};
const audio=new Audio();audio.preload='metadata';
const ownAudio=$('ownAudio');
function req(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
async function all(store){return req(tx(store).getAll())}async function get(store,key){return req(tx(store).get(key))}async function put(store,v){return req(tx(store,'readwrite').put(v))}async function del(store,key){return req(tx(store,'readwrite').delete(key))}
function uid(){return crypto.randomUUID()}function fmt(s){if(!isFinite(s))return'0:00';s=Math.max(0,s);return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')}
function blobUrl(blob){return blob?URL.createObjectURL(blob):''}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=e=>{const d=e.target.result;for(const s of ['lessons','pages','audios','practices','recordings'])if(!d.objectStoreNames.contains(s))d.createObjectStore(s,{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
async function seed(){for(let i=1;i<=26;i++)if(!await get('lessons','L'+i))await put('lessons',{id:'L'+i,num:i,title:`Lesson ${String(i).padStart(2,'0')}`})}
function lessonLabel(n){return`Lesson ${String(n).padStart(2,'0')}`}function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function init(){await openDB();await seed();fillLessons();loadTheme();bind();await renderLesson()}
function fillLessons(){$('lessonSelect').innerHTML=Array.from({length:26},(_,i)=>`<option value="${i+1}">${lessonLabel(i+1)}</option>`).join('');$('lessonSelect').value=state.lesson}
function pageHTML(p){const hidden=p.visible===false;const url=blobUrl(p.blob);return `<article class="page ${hidden?'hiddenPage':''}" ${hidden?'hidden':''} data-page="${p.id}"><div class="pageHead"><span class="pageNum">P.${esc(p.pageNo||'—')}</span><div class="pageActions"><button onclick="togglePage('${p.id}')">🙈 非表示</button><button onclick="addPractice('${p.id}')">＋Practice</button><button class="danger" onclick="deletePage('${p.id}')">🗑 画像削除</button></div></div>${url?`<img src="${url}" alt="${esc(p.name||'ページ画像')}">`:''}<div id="prs-${p.id}"></div></article>`}
async function renderLesson(){state.book=false;$('bookView').hidden=true;$('pages').hidden=false;$('editToolbar').hidden=false;$('audioManager').hidden=true;$('bookBtn').textContent='📖 本を読む';const lesson=await get('lessons','L'+state.lesson);$('lessonTitle').innerHTML=`<h2>${lessonLabel(state.lesson)}</h2><div class="editHint">1ページ目は常に表示。2ページ目以降は非表示⇄再表示できます。</div>`;const pages=(await all('pages')).filter(p=>p.lesson===state.lesson).sort((a,b)=>a.order-b.order);$('pages').innerHTML=pages.map(pageHTML).join('')||`<div class="page empty">このLessonにはまだページがありません。<br>「＋ページ画像」から追加してください。</div>`;await loadPractices();await renderHiddenPages()}
async function loadPractices(){const prs=(await all('practices')).filter(p=>p.lesson===state.lesson);for(const p of prs){const el=document.querySelector(`#prs-${p.pageId}`);if(!el)continue;const au=p.audioId?await get('audios',p.audioId):null;el.insertAdjacentHTML('beforeend',`<div class="practice"><div class="practiceTop"><span class="practiceName">${esc(p.name)}</span><div class="practiceBtns"><button onclick="playPractice('${p.id}')">▶️</button><button onclick="editPractice('${p.id}')">編集</button><button onclick="recordPractice('${p.id}')">🎙️</button><button class="danger" onclick="deletePractice('${p.id}')">🗑</button></div></div><div class="audioChip">${au?esc(au.name):'音声未登録'}</div></div>`)}}
async function addPages(files){if(!files?.length)return;let pages=(await all('pages')).filter(p=>p.lesson===state.lesson);let order=pages.length;for(const f of files){await put('pages',{id:uid(),lesson:state.lesson,order:order,pageNo:guessPageNo(f.name,order+1),visible:true,blob:f,name:f.name});order++}$('pageFiles').value='';await renderLesson()}
function guessPageNo(name,n){const m=name.match(/(?:P|p|page|ページ)[ _-]?(\d+)/);return m?m[1]:n}
async function deletePage(id){if(!confirm('このページ画像を削除しますか？\nこのページのPracticeも削除されます。'))return;const prs=(await all('practices')).filter(p=>p.pageId===id);for(const p of prs)await del('practices',p.id);await del('pages',id);await renderLesson()}
async function togglePage(id){const p=await get('pages',id);if(!p)return;const pages=(await all('pages')).filter(x=>x.lesson===p.lesson).sort((a,b)=>a.order-b.order);if(p.id===pages[0]?.id)return alert('Lessonの1ページ目は常に表示されます。');p.visible=false;await put('pages',p);const el=document.querySelector(`[data-page="${id}"]`);if(el){el.hidden=true;el.classList.add('hiddenPage')}await renderHiddenPages()}
async function restorePage(id){const p=await get('pages',id);if(!p)return;p.visible=true;await put('pages',p);const el=document.querySelector(`[data-page="${id}"]`);if(el){el.hidden=false;el.classList.remove('hiddenPage')}await renderHiddenPages()} 
async function renderHiddenPages(){const list=(await all('pages')).filter(p=>p.lesson===state.lesson&&p.visible===false).sort((a,b)=>a.order-b.order);$('hiddenPageList').innerHTML=list.length?list.map(p=>`<div class="hiddenRow"><span>P.${esc(p.pageNo||'—')}　${esc(p.name||'ページ画像')}</span><button onclick="restorePage('${p.id}')">👁 再表示</button></div>`).join(''):'<div class="empty">非表示のページはありません。</div>'}
async function addPractice(pageId){const p=await get('pages',pageId);const x={id:uid(),pageId,lesson:p.lesson,name:'Practice',audioId:null};await put('practices',x);await renderLesson();await editPractice(x.id)}
async function editPractice(id){state.editing=id;const p=await get('practices',id);$('practiceName').value=p.name;const audios=(await all('audios')).filter(a=>a.lesson===p.lesson).sort((a,b)=>a.order-b.order);$('audioSelect').innerHTML='<option value="">音声なし</option>'+audios.map(a=>`<option value="${a.id}" ${a.id===p.audioId?'selected':''}>${esc(a.name)}</option>`).join('');$('editDialog').showModal()}
async function savePractice(){const p=await get('practices',state.editing);p.name=$('practiceName').value.trim()||'Practice';p.audioId=$('audioSelect').value||null;await put('practices',p);await renderLesson()}
async function deletePractice(id){if(!confirm('このPracticeを削除しますか？（音声ファイル自体は削除しません）'))return;await del('practices',id);await renderLesson()}
async function addAudios(files){if(!files?.length)return;const audios=(await all('audios')).filter(a=>a.lesson===state.lesson);let order=audios.length;for(const f of files){await put('audios',{id:uid(),lesson:state.lesson,order:order++,name:f.name,blob:f})}$('audioFiles').value='';await renderLesson();await showAudioManager()}
async function showAudioManager(){const list=(await all('audios')).filter(a=>a.lesson===state.lesson).sort((a,b)=>a.order-b.order);$('audioList').innerHTML=list.length?list.map(a=>`<div class="audioRow"><span class="name">${esc(a.name)}</span><div><button onclick="playAudioById('${a.id}')">▶️</button><button class="danger" onclick="deleteAudio('${a.id}')">🗑 削除</button></div></div>`).join(''):'<div class="empty">このLessonには音声がありません。</div>';$('audioDialog').showModal()}
async function playAudioById(id){const a=await get('audios',id);if(a)startAudio(a,a.name)}
async function deleteAudio(id){if(!confirm('この音声を削除しますか？\n登録済みPracticeの音声指定も解除されます。'))return;const prs=(await all('practices')).filter(p=>p.audioId===id);for(const p of prs){p.audioId=null;await put('practices',p)}await del('audios',id);await showAudioManager();await renderLesson()}
async function startAudio(a,label){state.current=a;state.queue=[a];state.idx=0;state.A=null;state.B=null;state.ab=false;updateAB();audio.src=blobUrl(a.blob);audio.playbackRate=Number($('speed').value);audio.currentTime=0;$('now').textContent=label||a.name;await audio.play()}
async function playPractice(id){const p=await get('practices',id);if(!p?.audioId)return alert('このPracticeには音声がありません。編集から音声を選んでください。');const a=await get('audios',p.audioId);await startAudio(a,p.name)}
audio.ontimeupdate=()=>{$('cur').textContent=fmt(audio.currentTime);$('dur').textContent=fmt(audio.duration);$('seek').value=audio.duration?audio.currentTime/audio.duration*1000:0;if(state.ab&&state.B!==null&&audio.currentTime>=state.B){audio.currentTime=state.A??0;audio.play()}};
audio.onended=async()=>{if(state.ab)return;if(state.repeat){audio.currentTime=state.A??0;await audio.play()}};
function updateAB(){$('markA').textContent='A:'+(state.A===null?'—':fmt(state.A));$('markB').textContent='B:'+(state.B===null?'—':fmt(state.B));$('ab').textContent=state.ab?'A-B ON':'A-B OFF'}
async function recordPractice(id){state.recording=id;const p=await get('practices',id);$('recordTarget').textContent=p.name;const rs=(await all('recordings')).filter(r=>r.practiceId===id).sort((a,b)=>b.created-a.created)[0];if(rs){ownAudio.src=blobUrl(rs.blob);ownAudio.hidden=false;$('deleteRecording').hidden=false}else{ownAudio.removeAttribute('src');ownAudio.hidden=true;$('deleteRecording').hidden=true}$('recordState').textContent='待機中';$('recordDialog').showModal()}
let rec,chunks=[];function bestMime(){return ['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(x=>MediaRecorder.isTypeSupported?.(x))||''}
$('recordStart').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=bestMime();rec=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:rec.mimeType||'audio/webm'});const old=(await all('recordings')).filter(r=>r.practiceId===state.recording);for(const r of old)await del('recordings',r.id);await put('recordings',{id:uid(),practiceId:state.recording,created:Date.now(),blob});ownAudio.src=blobUrl(blob);ownAudio.hidden=false;$('deleteRecording').hidden=false;$('recordState').textContent='保存しました'};rec.start();$('recordStart').disabled=true;$('recordStop').disabled=false;$('recordState').textContent='録音中…';const p=await get('practices',state.recording);if(p?.audioId){const a=await get('audios',p.audioId);audio.src=blobUrl(a.blob);audio.currentTime=0;audio.playbackRate=Number($('speed').value);await audio.play()}}catch(e){alert('マイクを許可できませんでした。iPhoneではHTTPSページでマイクを許可してください。')}};
$('recordStop').onclick=()=>{if(rec&&rec.state!=='inactive')rec.stop();$('recordStart').disabled=false;$('recordStop').disabled=true};$('refOnly').onclick=()=>audio.play();$('ownOnly').onclick=()=>ownAudio.play();$('bothPlay').onclick=()=>{audio.play();ownAudio.play()};$('deleteRecording').onclick=async()=>{for(const r of (await all('recordings')).filter(r=>r.practiceId===state.recording))await del('recordings',r.id);ownAudio.removeAttribute('src');ownAudio.hidden=true;$('deleteRecording').hidden=true};$('closeRecord').onclick=()=>$('recordDialog').close();
async function openBook(){state.book=true;$('editToolbar').hidden=true;$('pages').hidden=true;$('lessonTitle').innerHTML='';$('audioManager').hidden=true;$('bookView').hidden=false;$('bookBtn').textContent='✏️ 本を編集';const pages=(await all('pages')).filter(p=>p.visible!==false).sort((a,b)=>a.lesson-b.lesson||a.order-b.order);let last=0;$('bookView').innerHTML=pages.map(p=>{const h=p.lesson!==last?`<div class="lessonHeader">${lessonLabel(p.lesson)}</div>`:'';last=p.lesson;return h+pageHTMLBook(p)}).join('')||'<div class="page empty">ページがありません。</div>';await loadPracticesBook()} 
function closeBook(){state.book=false;$('bookBtn').textContent='📖 本を読む';renderLesson()}
function pageHTMLBook(p){return `<article class="page" data-page="${p.id}"><div class="pageHead"><span class="pageNum">P.${esc(p.pageNo||'—')}</span></div>${p.blob?`<img src="${blobUrl(p.blob)}" alt="${esc(p.name||'ページ画像')}">`:''}<div id="bookprs-${p.id}"></div></article>`}
async function loadPracticesBook(){for(const p of await all('practices')){const el=document.querySelector(`#bookprs-${p.pageId}`);if(!el)continue;const a=p.audioId?await get('audios',p.audioId):null;el.insertAdjacentHTML('beforeend',`<div class="practice"><div class="practiceTop"><span class="practiceName">${esc(p.name)}</span><div class="practiceBtns"><button onclick="playPractice('${p.id}')">▶️</button><button onclick="recordPractice('${p.id}')">🎙️</button></div></div><div class="audioChip">${a?esc(a.name):'音声未登録'}</div></div>`)}}
function loadTheme(){const saved=localStorage.getItem('eigomimi-theme');state.dark=saved!=='light';applyTheme()}function applyTheme(){document.body.classList.toggle('light',!state.dark);$('themeBtn').textContent=state.dark?'☀️':'🌙';localStorage.setItem('eigomimi-theme',state.dark?'dark':'light')}
function bind(){$('themeBtn').onclick=()=>{state.dark=!state.dark;applyTheme()};$('addPageBtn').onclick=()=>$('pageFiles').click();$('pageFiles').onchange=e=>addPages(e.target.files);$('addAudioBtn').onclick=()=>$('audioFiles').click();$('audioFiles').onchange=e=>addAudios(e.target.files);$('audioManagerBtn').onclick=showAudioManager;$('closeAudioDialog').onclick=()=>$('audioDialog').close();$('lessonSelect').onchange=async e=>{state.lesson=Number(e.target.value);await renderLesson()};$('bookBtn').onclick=()=>state.book?closeBook():openBook();$('hideInfoBtn').onclick=async()=>{await renderHiddenPages();$('hiddenDialog').showModal()};$('closeHiddenDialog').onclick=()=>$('hiddenDialog').close();$('savePractice').onclick=e=>{e.preventDefault();savePractice();$('editDialog').close()};$('play').onclick=()=>audio.paused?audio.play():audio.pause();audio.onplay=()=>$('play').textContent='⏸';audio.onpause=()=>$('play').textContent='▶️';$('seek').oninput=()=>{if(audio.duration)audio.currentTime=Number($('seek').value)/1000*audio.duration};$('restart').onclick=()=>{audio.currentTime=state.A??0;audio.play()};$('repeat').onclick=()=>{state.repeat=!state.repeat;$('repeat').style.background=state.repeat?'#e91e8c':''};$('speed').onchange=()=>audio.playbackRate=Number($('speed').value);$('setA').onclick=()=>{state.A=audio.currentTime;updateAB()};$('setB').onclick=()=>{state.B=audio.currentTime;updateAB()};$('ab').onclick=()=>{state.ab=!state.ab;if(state.ab&&state.A===null)state.A=audio.currentTime;if(state.ab&&state.B===null&&isFinite(audio.duration))state.B=audio.duration;updateAB()}}
window.togglePage=togglePage;window.addPractice=addPractice;window.editPractice=editPractice;window.playPractice=playPractice;window.recordPractice=recordPractice;window.deletePage=deletePage;window.deletePractice=deletePractice;window.playAudioById=playAudioById;window.deleteAudio=deleteAudio;window.restorePage=restorePage;
init().catch(e=>alert('初期化に失敗しました: '+e.message));
